name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js and dependencies
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Set up environment variables
      run: echo "mongoUrl=${{ secrets.MONGOURL }}" >> $GITHUB_ENV

    - name: Run tests with Jest
      run: |
        npm test
        jest --detectOpenHandles
